cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'homebrew/services'

brew 'ansible'
brew 'awscli'
brew 'bash-completion'
brew 'chruby'
brew 'git'
brew 'kubernetes-cli'
brew 'mas'
brew 'nmap'
brew 'packer'
brew 'pv'
brew 'python'
brew 'ruby-install'

cask 'alfred'
cask 'arq'
cask 'atom'
cask 'aws-vault'
cask 'dash'
cask 'discord'
cask 'docker'
cask 'google-chrome'
cask 'iterm2'
cask 'keybase'
cask 'kitematic'
cask 'minikube'
cask 'omnifocus'
cask 'paw'
cask 'shimo'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'

mas 'Pixelmator', id: 407963104 if `mas account`.chomp == 'chris@bbck.net'
