[theme]
builtin = "Kanagawa"
community_palette = "Kanagawa Paper"
source = "community"
wallpaper_scheme = "muted"

[theme.templates]
builtin_ids = ["gtk3", "gtk4"]

[wallpaper.default]
path = "/home/chris/Pictures/Wallpapers/lamp-post.jpg"

[bar]
order = ["main"]

[bar.main]
start = ["launcher"]
center = ["clock"]
end = ["tray", "notifications", "claudecode", "network", "volume", "session"]
margin_ends = 860

[bar.main.monitor.DP-4]
enabled = false

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "mic_mute"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "clipboard"

[idle]
behavior_order = ["lock", "screen-off", "custom-suspend"]

[idle.behavior.lock]
action = "lock"
timeout = 900  # 15 min

[idle.behavior.screen-off]
action = "screen_off"
timeout = 1800  # 30 min

[idle.behavior.custom-suspend]
action = "command"
timeout = 3600  # 60 min
# Turn the display back on before suspend
command = "hyprctl dispatch 'hl.dsp.dpms({action=\"enable\"})' && sleep 2 && systemctl suspend"

[lockscreen]
monitors = ["DP-1"]

[notification]
monitors = ["DP-1"]

[plugins]
enabled = ["jrohland/claudecode"]
# To update community plugins `noctalia msg plugins update community`
auto_update = "official"

[shell]
launch_apps_custom_command = "uwsm-app -- $CMD"
polkit_agent = true

[shell.launcher.providers.calculator]
global = false

[shell.screenshot]
directory = "/home/chris/Pictures/Screenshots"

[weather]
unit = "imperial"

[widget.claudecode]
type = "jrohland/claudecode:pill"

[widget.network]
show_label = false

[widget.tray]
drawer = true

[widget.workspaces]
label_source = "name"
