theme {
    color_scheme = $HOME/.config/hypr/kanagawa-paper.colors
    icon_theme = rose-pine-icons
    style = Fusion
    font = SF Pro Text
    font_size = 10
    font_fixed = JetBrainsMono Nerd Font
    font_fixed_size = 10
}
